export const SET_TODAY = 'SET_TODAY';
export const SET_CURRENT_DATE_POINT = 'SET_CURRENT_DATE_POINT';
export const SET_CURRENT_VIEW = 'SET_CURRENT_VIEW';

export const GET_EVENTS_BEGIN = 'GET_EVENTS_BEGIN';
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
export const GET_EVENTS_FAILURE = 'GET_EVENTS_FAILURE';
