export const SET_TODAY = 'SET_TODAY';
export const SET_CURRENT_DATE_POINT = 'SET_CURRENT_DATE_POINT';
export const SET_CURRENT_VIEW = 'SET_CURRENT_VIEW';
export const SET_CALENDAR_MODE = 'SET_CALENDAR_MODE';

export const GET_EVENTS_BEGIN = 'GET_EVENTS_BEGIN';
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';
export const GET_EVENTS_FAILURE = 'GET_EVENTS_FAILURE';

export const ADD_EVENT_BEGIN = 'ADD_EVENT_BEGIN';
export const ADD_EVENT_SUCCESS = 'ADD_EVENT_SUCCESS';
export const ADD_EVENT_FAILURE = 'ADD_EVENT_FAILURE';

export const SET_EDITED_EVENT = 'SET_EDITED_EVENT';

export const EDIT_EVENT_BEGIN = 'EDIT_EVENT_BEGIN';
export const EDIT_EVENT_SUCCESS = 'EDIT_EVENT_SUCCESS';
export const EDIT_EVENT_FAILURE = 'EDIT_EVENT_FAILURE';

export const DELETE_EVENT_BEGIN = 'DELETE_EVENT_BEGIN';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_FAILURE = 'DELETE_EVENT_FAILURE';
